var base_url="",base_url_image="";String.prototype.replaceAll=function(b,a){for(var c=this.replace(b,a);-1!==c.indexOf(b);)c=c.replace(b,a);return c};String.prototype.toCamel=function(){for(var b=this.split("-"),a=0;a<b.length;a++)b[a]=b[a].charAt(0).toUpperCase()+b[a].slice(1,b[a].length);return b.join("")};String.prototype.memberize=function(b){var a=this.toCamel();a=a.charAt(0).toLowerCase()+a.slice(1,this.length);b&&(a="__"+a);return a};String.prototype.classify=function(){};
String.prototype.ucWords=function(){for(var b=this.split(" "),a=b.length,c=0;c<a;c++)b[c]=b[c].charAt(0).toUpperCase()+b[c].slice(1,b[c].length);return b.join(" ")};$.fn.any=function(b){var a=!1;$.each(object,function(b,e){if(e)return a=!0,!1});return a};
$.fn.toObject=function(){var b=this.serializeArray(),a={data:{}};b.shift();$.each(b,function(b,e){var d=e.name.match(/\[(\w*)\]/g);var c={};null!==d&&1<d.length&&(c={model:d.shift().replaceAll("[","").replaceAll("]",""),name:d.pop().replaceAll("[","").replaceAll("]","")},d.length&&(c.index=d[0].replaceAll("[","").replaceAll("]","")));d=c;"undefined"===typeof a.data[d.model]&&(a.data[d.model]={});"undefined"!==typeof d.index?("undefined"===typeof a.data[d.model][d.index]&&(a.data[d.model][d.index]=
{}),a.data[d.model][d.index][d.name]=e.value):a.data[d.model][d.name]=e.value});return a};$.fn.toJSON=function(){return JSON.stringify(this.toObject())};$.fn.out=function(b){for(var a=this,c=0;c<b;c++)a=a.parent();return a};function trimFunction(b){return b.replace(/^\s+|\s+$/gm,"")}function randomizer(b,a){return Math.floor(Math.random()*(1+a-b))+b}function setCookie(b,a,c){var e=new Date;e.setTime(e.getTime()+1E3*c);c="expires="+e.toUTCString();document.cookie=b+"="+a+"; "+c}
function getCookie(b){b+="=";for(var a=document.cookie.split(";"),c=0;c<a.length;c++){for(var e=a[c];" "==e.charAt(0);)e=e.substring(1);if(0==e.indexOf(b))return e.substring(b.length,e.length)}return""}
$(function(){base_url=$("#base_url").attr("value");base_url_image=$("#base_url_image").attr("value");$.each(["show","hide"],function(b,a){var c=$.fn[a];$.fn[a]=function(){this.trigger(a);return c.apply(this,arguments)}});equalheight=function(b){var a=0,c=0,e=[],d;$(b).each(function(){d=$(this);$(d).height("auto");topPostion=d.position().top;if(c!=topPostion){for(currentDiv=0;currentDiv<e.length;currentDiv++)e[currentDiv].height(a);e.length=0;c=topPostion;a=d.height();e.push(d)}else e.push(d),a=a<
d.height()?d.height():a;for(currentDiv=0;currentDiv<e.length;currentDiv++)e[currentDiv].height(a)})};$(window).load(function(){equalheight("#product-list > li")});$(window).resize(function(){equalheight("#product-list > li")});$("#a-reload").click(function(){var b=$("#img-captcha");b.attr("src",b.attr("src")+"?"+Math.random());return!1});$("#captcha-input").keyup(function(){$(this).removeClass("error");$(this).next().remove()});$(document).on("click",".close",function(){$(".message").removeClass("animated bounceInDown").addClass("animated bounceOutUp");
setTimeout(function(){$(".message").removeClass("animated bounceOutUp").hide()},1E3)});$(document).on("click",".btn-cart-continue",function(){$(".wrapper-list-products-shopping-cart").hide();setTimeout(function(){$(".wrapper-list-products-shopping-cart").prop("style","")},100)});$("#FormSelectAll").change(function(){$(this).is(":checked")?$(".delete").prop("checked",!0):$(".delete").prop("checked",!1)});$(".sidebar").find(".show-sub-category").each(function(){$(this).parents("li.has-submenu").addClass("show-sub-category")});
if($("body").hasClass("layout-mobile"))return!1;$(document).on("click",".fb-chat-header",function(){$(this).parent(".fb-chat-wrapper").toggleClass("active");$(this).fadeToggle()});$(document).on("click",".fb-chat-icon-close",function(){$(".fb-chat-wrapper").removeClass("active");$(".fb-chat-wrapper .fb-chat-header").fadeIn()});if(Modernizr.input.placeholder)return!1;$(":input:not(select, textarea, :hidden)").each(function(){var b=$(this).attr("placeholder");""==$(this).val()&&void 0!=b&&($(this).val(b),
$(this).on("focusin",function(){if($(this).val()==b)$(this).val("");else return!1}).on("focusout",function(){if(""==$(this).val())$(this).val(b);else return!1}))})});