/*
     D Loja Virtual
 @link          http://www.dlojavirtual.com
 @package       app.FrontEnd.Js
 @since         v 1.0
 @author        Bruno Lehnen Simões
*/
var ProductModel={__imgCache:{},__imgDefaults:{},__cacheImg:function(a,b,d){var c=this;"undefined"==typeof this.__imgCache[a]?b?c.__imgCache[a]=$.clone(b):(c.__imgCache[a]=document.createElement("img"),App.isValidCallback(d)&&$(c.__imgCache[a]).load(function(){d(c.__imgCache[a])}),c.__imgCache[a].src=base_url_image+"/sku/thumb_"+a):App.isValidCallback(d)&&d(this.__imgCache[a])},__getCombination:function(a){return a.name.split("[")[4].slice(0,-1)},__getProductId:function(a){return a.name.split("[")[3].slice(0,
-1)},__setDefaultImg:function(a,b){this.__imgDefaults[a]=b},init:function(){var a=this;$(".product-image").each(function(b,d){var c=$(d.parentNode.parentNode).data("id"),e=null==$(this).children("a").children("img").attr("src")?$(this).children("a").children("img").attr("data-src").split("/").pop().split("_").pop():$(this).children("a").children("img").attr("src").split("/").pop().split("_").pop();a.__cacheImg(e,d);a.__setDefaultImg(c,e)})},getCacheImg:function(a){return this.__imgCache[a]},getDefaultImg:function(a,
b){return"undefined"!=typeof b&&b?this.getCacheImg(this.__imgDefaults[a]):this.__imgDefaults[a]},getQuestions:function(a){var b=[],d=[];0<a.length&&a.each(function(a,e){var c=$(e).prop("alt"),f=$(e).attr("data-minlength"),g=$(e).attr("data-length"),h=$(e).val();"float-two"==c?(c="number",h=parseFloat(h.replace(",",".")),f=parseFloat(f),g=parseFloat(g)):("number"==c&&(h=parseInt(h)),f=parseInt(f),g=parseInt(g));"number"==c&&0!=f&&(h<f||0>h)?(c=$(e).closest(".row").children(".product-question-item-title").html(),
"undefined"==typeof c&&(c=$(e).closest(".product-question-action").children(".product-question-item-title").html()),d[0]={error:!0,msg:"O valor m\u00ednimo para "+c+" \u00e9 "+f}):"number"==c&&0!=g&&(h>g||0>h)?(c=$(e).closest(".row").children(".product-question-item-title").html(),"undefined"==typeof c&&(c=$(e).closest(".product-question-action").children(".product-question-item-title").html()),d[0]={error:!0,msg:"O valor m\u00e1ximo para "+c+" \u00e9 "+g}):0!=g&&h.length>g?(c=$(e).closest(".row").children(".product-question-item-title").html(),
d[0]={error:!0,msg:"O tamanho m\u00e1ximo para "+c+" \u00e9 "+g}):""!==$(e).val()&&(b[b.length]={id:$(e).data("question-id"),pergunta:$(e).data("question"),valor:$(e).val()})});return 0<d.length?d:b},getChecked:function(a){var b=this,d=[];$(a).children("li").children("input:checked").each(function(a,e){d[d.length]={produto_id:b.__getProductId(e),order:$(e).data("order"),atributo_id:e.value,combinacao_id:b.__getCombination(e),muda_vitrine:$(e).hasClass("active-combination")}});return d},getKitChecked:function(a,
b){var d=[];$.each(a,function(a,e){d[d.length]={id:$(e).attr("data-id"),produto_id:$(e).attr("data-product"),produto_estoque_id:$(e).attr("data-stock"),clicado:b==$(e).attr("data-id")?!0:!1}});return d},find:function(a,b,d){var c=this;a=JSON.stringify(a);var e=WsRouter.generateRoute(null,"produto","readVitrine",c.id);WsDispatcher.postRequest(e,{CombinacaoAtributo:a},b,function(a){App.isValidCallback(d)&&(a.img||(a.img=c.getDefaultImg(c.id)),c.__cacheImg(a.img,null,function(b){$(b).hasClass("product-image")?
(elementImg=document.createElement("img"),elementImg.src=base_url_image+"/sku/thumb_"+a.img,a.img=elementImg):a.img=b;d.call(c,a)}))})},find_det:function(a,b,d){a=JSON.stringify(a);var c=WsRouter.generateRoute("produto","combinacao","readDetalhamento",this.id);WsDispatcher.postRequest(c,{CombinacaoAtributo:a},b,d)},findKit:function(a,b,d,c,e){a=JSON.stringify(a);b=JSON.stringify(b);d=JSON.stringify(d);reqId=this.id;route=WsRouter.generateRoute("produto","combinacao","readKit",[reqId,this.amount]);
WsDispatcher.postRequest(route,{CombinacaoAtributo:a,Itens:b,ProdutoKit:d},c,e)},find_detUnidade:function(a,b,d,c){a=WsRouter.generateRoute(null,"produto","readDetalhamentoUnidade",a);WsDispatcher.postRequest(a,{quantidade:b},d,c)},hint:function(a,b,d){a=JSON.stringify({key:a});var c=WsRouter.generateRoute(null,"produto","hint");WsDispatcher.postRequest(c,{CatalogoProduto:a},b,function(a){CurrencyBehavior.formatProduct(a);App.initCallback(d,a,this)})},cartCreateProductKit:function(a,b,d,c){var e=
"undefined"!==typeof gtag,k="undefined"!==typeof fbq,f=this;a=JSON.stringify(a);b=JSON.stringify(b);route=WsRouter.generateRoute(null,"carrinhos","createProductKit",[f.id,f.kitId,f.amount]);WsDispatcher.postRequest(route,{CombinacaoAtributo:a,Pergunta:b},d,function(a){if(App.isValidCallback(c)&&a&&(a={CatalogoCarrinho:a},CurrencyBehavior.formatCart(a),c.call(f,a.CatalogoCarrinho),e&&gtag("event","add_to_cart"),k)){var b=[];b[b.length]=a.CatalogoCarrinho.estoque_id;fbq("track","AddToCart",{content_ids:b,
content_type:"product"})}})},cartCreateProductKitUnique:function(a,b,d){var c="undefined"!==typeof gtag,e="undefined"!==typeof fbq,k=this;route=WsRouter.generateRoute(null,"carrinhos","createProductKitUnique",[k.kitId,k.amount]);WsDispatcher.postRequest(route,{Estoque:a},b,function(a){if(App.isValidCallback(d)&&a&&(a={CatalogoCarrinho:a},CurrencyBehavior.formatCart(a),d.call(k,a.CatalogoCarrinho),c&&gtag("event","add_to_cart"),e)){var b=[];b[b.length]=a.CatalogoCarrinho.estoque_id;fbq("track","AddToCart",
{content_ids:b,content_type:"product"})}})},cartCreateProduct:function(a,b,d,c){var e="undefined"!==typeof gtag,k="undefined"!==typeof fbq,f=this;a=JSON.stringify(a);b=JSON.stringify(b);var g=f.gift,h=f.payLater,l=WsRouter.generateRoute(null,"carrinhos","createProduct",[f.id,f.amount]);WsDispatcher.postRequest(l,{CombinacaoAtributo:a,Pergunta:b,Lista:g,Depois:h},d,function(a){if(App.isValidCallback(c)&&a&&(a={CatalogoCarrinho:a},CurrencyBehavior.formatCart(a),c.call(f,a.CatalogoCarrinho),e&&gtag("event",
"add_to_cart"),k)){var b=[];b[b.length]=a.CatalogoCarrinho.estoque_id;fbq("track","AddToCart",{content_ids:b,content_type:"product"})}})},favoriteProduct:function(a,b,d){a=JSON.stringify({produto_id:this.id,produto_estoque_id:a});var c=WsRouter.generateRoute(null,"clientes","favoriteProduct",[]);WsDispatcher.postRequest(c,{Produto:a},b,d)}};